version: '3'
services:
  hugo:
    image: hugomods/hugo:base-0.140.0
    command: new site . --force --format yaml
    volumes:
      - .:/src
    ports:
      - "1313:1313"
    environment:
      - HUGO_ENVIRONMENT=development
