version: '3'
services:
  hugo:
    image: hugomods/hugo:dart-sass-base-0.140.0
    command: server --disableFastRender
    volumes:
      - .:/src
    ports:
      - "1313:1313"
    environment:
      - HUGO_ENVIRONMENT=development
